[package]
name = "equihash"
description = "The Equihash Proof-of-Work function"
version = "0.2.0"
authors = ["Jack Grigg <jack@z.cash>"]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies]
core2.workspace = true
blake2b_simd.workspace = true

[lib]
bench = false

[lints]
workspace = true

[features]
default = ["std"]
std = []
